<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($search)
    {
        return $this->createQueryBuilder("p")
                    ->where("p.name LIKE :search")
                    ->setParameter("search", "%" . $search . "%")
                    ->getQuery()
                    ->getResult();
    }
}
