fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /listes
        permanent: true
